# Generated by Django 4.1.4 on 2022-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='Username')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('school', models.CharField(max_length=50, verbose_name='School')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_member', models.BooleanField(default=False, verbose_name='Member')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
        ),
    ]
